# Generated by Django 4.0 on 2021-12-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('decription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updeted_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('is_publicated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'mesto',
                'verbose_name_plural': 'Mesta',
                'ordering': ['name'],
            },
        ),
    ]
